### ISSUE TITLE
models.resnet_baseline_re not found

### ISSUE THREAD

**Issue by ogutsevda** [HKU-MedAI/HIGT#4]
Hello,

I guess the resnet_baseline from CLAM was re-written but unfortunately this function is nowhere in the github repo. Could you provide it please?

Best!

**Comment by junjianli106** [comment]
Have you found this file or a solution?
@ogutsevda

**Comment by ogutsevda** [comment]
I have emailed the authors and they updated the repo with this file @junjianli106 👍

**Comment by junjianli106** [comment]
The authors added a nn.Linear(1024, out_shape) after their ResNet model, which appears to be randomly initialized. Are the features extracted in this way meaningful?


```
model_re = nn.Sequential(
        *[resnet_model, nn.Flatten(), nn.Linear(1024, out_shape)]
    )
```

**Comment by ogutsevda** [comment]
You're right, probably they aren't meaningful. Actually, the authors state in the paper that they had used KimiaNet in the feature extraction process and I asked about this in my email. They responded that they would update the repo again with the correct feature extraction code. You can reopen the issue if you want 👍

**Comment by junjianli106** [comment]
Thank you for your patient response.
